title: Project title in sentence case
hero_image: images/banner.png
description: A short description of the project
listed: false
pdf: false
steps:
  - title: What you will make
  - title: Make some noise
  - title: Foil switch
  - title: Make a puppet
  - title: Embed the switch
  - title: Attach board
  - title: Rotate the puppet
  - title: Make some noise
    completion:
      - engaged      
  - title: Challenge
    challenge: true
    completion:
      - external
