title: Interactive sock puppet
hero_image: images/banner.png
description: A short description of the project
listed: false
pdf: false
steps:
  - title: What you will make
  - title: Mouth closed switch
  - title: Open switch 
  - title: Add buzzer
  - title: Make the puppet
  - title: Add a mouth and eyes
  - title: Hairstyle
  - title: Embed the switch
  - title: Attach board 
  - title: Change sounds on rotate 
  - title: Add sad sound 
    completion:
      - engaged      
  - title: Challenge
    challenge: true
    completion:
      - external
