title: Sock puppet
hero_image: images/banner.png
description: Make a puppet make some noise!
listed: true
pdf: false
steps:
  - title: What you will make
  - title: Make a foil switch
  - title: Add a buzzer
  - title: Make the puppet
  - title: Add hair
  - title: Embed the switch
  - title: Attach board 
  - title: 'Challenge: Sound and gestures'
    completion:
      - engaged      
  - title: More challenges
    challenge: true
    completion:
      - external
